// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqdozxspumgoddxknaxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZG96eHNwdW1nb2RkeGtuYXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDk3MjUsImV4cCI6MjA2NzcyNTcyNX0.SNA7o8UpDTBfw7PU81MGTty4n8bHSxj-rj3aamdcwNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});